import { Capacitor } from '@capacitor/core';
import type {
  ActionPerformed,
  Channel,
  LocalNotificationSchema,
  ScheduleOptions,
} from '@capacitor/local-notifications';
import { LocalNotifications } from '@capacitor/local-notifications';
import type { Departure, Exam, Milestone, Sprint } from '../db/types';
import { computeAlarmTimes } from '../lib/alarmTimes';
import { formatTime } from '../lib/format';
import { HORIZON_DAYS, calendarDates, occurrenceDates } from '../lib/recurrence';
import { logEvent } from '../lib/eventLog';

// The ONLY file in this app that imports @capacitor/local-notifications
// (increment-4 spec) — every screen goes through the functions exported
// here, so the plugin's real API surface only has one place to change if it
// moves under us on a future upgrade. Every export below is safe to call on
// a plain web build: it either no-ops or falls through to the plugin's own
// (harmless, in-memory) web implementation, gated by
// Capacitor.isNativePlatform() so dev mode never touches native code paths.

// v2 ids (landscape focus + audio cues increment, 0.22.0): a channel's
// `sound` is set once at createChannel() and is then IMMUTABLE for the
// lifetime of that channel id - see NotificationChannelManager.createChannel
// in the plugin's Android source (node_modules/@capacitor/local-notifications/
// android/.../NotificationChannelManager.java): `setSound()` is only ever
// called inside createChannel, never again, and Android itself enforces this
// at the OS level once a channel exists. The only way to attach the two new
// runway_staged.wav/runway_leave.wav chimes (generated by
// scripts/generate-chimes.py) to notifications that were already using the
// old default-sound channels is a NEW channel id - hence the '-2' suffix
// rather than reusing 'runway-staged'/'runway-leave' in place. The tradeoff,
// named rather than glossed over: anyone who'd already customized the old
// channels' sound/vibration in Android Settings loses that customization
// once, since the v2 channels start over at this plugin's defaults (noted in
// CHANGELOG.md under 0.22.0).
const STAGED_CHANNEL_ID = 'runway-staged-2';
const LEAVE_CHANNEL_ID = 'runway-leave-2';
// The old, pre-0.22.0 ids - kept only so ensureChannels can delete them
// below (orphaned channels otherwise linger forever in Android Settings,
// since there's no other UI path that ever removes a channel once created).
const OLD_STAGED_CHANNEL_ID = 'runway-staged';
const OLD_LEAVE_CHANNEL_ID = 'runway-leave';
const SLOT_COUNT = 4;
const MS_PER_MINUTE = 60_000;

/**
 * F2 (recover-instead-of-forfeit spec): the action type attached ONLY to
 * slot 0's "Start getting ready." notification (see the comment where it's
 * assigned in scheduleDepartureAlarms below for why the other three slots
 * deliberately don't get this). One action, `SNOOZE_ACTION_ID` — its
 * `title` is the literal button label Android renders.
 */
const START_ACTION_TYPE_ID = 'runway-start-alarm';
const SNOOZE_ACTION_ID = 'snooze-10';
const SNOOZE_MINUTES = 10;

let channelsReady = false;

/**
 * Creates the two notification channels Android needs before it will show
 * anything on a per-channel importance/sound, and registers the snooze
 * action type (F2) alongside them. Idempotent per JS session via
 * `channelsReady` — Android channel settings are sticky after first
 * creation anyway (the user can retune sound/vibration in system settings
 * afterwards; re-creating with the same id does not reset that), so there's
 * nothing to gain from calling this more than once per launch; the same
 * reasoning covers registerActionTypes, which the plugin's .d.ts doesn't
 * document as harmful to call repeatedly but which also has nothing to
 * gain from it.
 */
async function ensureChannels(): Promise<void> {
  if (!Capacitor.isNativePlatform() || channelsReady) return;
  channelsReady = true;

  // Channel.sound's format (plugin .d.ts, definitions.d.ts): "The file name
  // of a sound file should be specified relative to the android app
  // res/raw directory" — e.g. "jingle.wav". Confirmed against the plugin's
  // Android source (NotificationChannelManager.createChannel): it strips
  // everything from the last '.' onward before building the
  // android.resource://<package>/raw/<name> URI, so "runway_staged.wav" and
  // "runway_staged" both resolve to the same res/raw/runway_staged.wav —
  // the extension here is kept for readability, matching the .d.ts's own
  // "jingle.wav" example, not because it's required.
  const staged: Channel = {
    id: STAGED_CHANNEL_ID,
    name: 'Getting ready',
    description: 'Getting-ready stages',
    importance: 3, // IMPORTANCE_DEFAULT
    sound: 'runway_staged.wav',
  };
  const leave: Channel = {
    id: LEAVE_CHANNEL_ID,
    name: 'Leave now',
    description: 'Leave now',
    importance: 4, // IMPORTANCE_HIGH — heads-up banner + sound
    vibration: true,
    sound: 'runway_leave.wav',
  };
  await Promise.all([
    LocalNotifications.createChannel(staged),
    LocalNotifications.createChannel(leave),
    LocalNotifications.registerActionTypes({
      types: [{ id: START_ACTION_TYPE_ID, actions: [{ id: SNOOZE_ACTION_ID, title: 'Snooze 10 min' }] }],
    }),
    // Deletes the pre-0.22.0 channels now that their replacements exist —
    // deleteChannel IS exposed by this plugin (LocalNotificationsPlugin.
    // deleteChannel(args: { id: string }), confirmed in definitions.d.ts and
    // backed by NotificationChannelManager.deleteChannel calling Android's
    // own NotificationManager.deleteNotificationChannel). Safe to call
    // unconditionally on every launch: deleting an id that's already gone
    // (every launch after the first, once these are gone) is a silent no-op
    // on Android, the same "safe to call unconditionally" shape every
    // cancel() call in this file already relies on.
    LocalNotifications.deleteChannel({ id: OLD_STAGED_CHANNEL_ID }),
    LocalNotifications.deleteChannel({ id: OLD_LEAVE_CHANNEL_ID }),
  ]);
}

/**
 * Requests the Android 13+ runtime POST_NOTIFICATIONS permission (via the
 * plugin's checkPermissions/requestPermissions — there is no separate
 * "post notifications" method; this single `display` permission covers it).
 * Resolves to `true` immediately on web/dev. Call lazily — the first time a
 * departure is saved, never at app launch — per CLAUDE.md's "no permission
 * ambush on first open".
 */
export async function ensurePermissions(): Promise<boolean> {
  if (!Capacitor.isNativePlatform()) return true;
  await ensureChannels();

  const current = await LocalNotifications.checkPermissions();
  if (current.display === 'granted') return true;

  const requested = await LocalNotifications.requestPermissions();
  return requested.display === 'granted';
}

/**
 * Whether Runway currently has permission to post notifications at all —
 * distinct from `ensurePermissions()`, which *requests* permission (and
 * therefore surfaces the Android system dialog); this only *reads* the
 * current state, so it's safe to call from a passive Home-screen banner
 * check without accidentally re-prompting the user. 'granted' on web/dev,
 * same reasoning as `getExactAlarmStatus` below — there's no such
 * permission to check outside native, and a banner should never appear
 * there.
 */
export async function getNotificationPermissionStatus(): Promise<'granted' | 'denied'> {
  if (!Capacitor.isNativePlatform()) return 'granted';
  const current = await LocalNotifications.checkPermissions();
  return current.display === 'granted' ? 'granted' : 'denied';
}

/**
 * djb2 string hash folded to an unsigned 32-bit int. Used only to turn a
 * departure's UUID into a deterministic number — this is not a
 * cryptographic hash, collisions are theoretically possible, and that's an
 * acceptable tradeoff here (a collision would at worst cancel/overwrite
 * another departure's alarm at the same slot, not corrupt data).
 */
function hashString(input: string): number {
  let hash = 5381;
  for (let i = 0; i < input.length; i++) {
    hash = (hash * 33) ^ input.charCodeAt(i);
  }
  return hash >>> 0; // coerce to unsigned 32-bit
}

/**
 * Deterministic notification id for a (departureId, slot) pair — needed so
 * cancelDepartureAlarms() can recompute the same four ids on a fresh app
 * launch without having the original ScheduleResult around (Dexie only
 * stores the Departure, not which notification ids were scheduled for it).
 *
 * Android notification ids are signed 32-bit ints. Folding the hash into 29
 * bits (`% 0x1fffffff`, i.e. mod 2^29 - 1) before `* SLOT_COUNT(4) + slot`
 * keeps the result inside the positive 31-bit range — worst case
 * 0x1fffffff * 4 + 3 = 2147483647 = 2^31 - 1 — with no overlap between the
 * four slots of the same departure.
 */
export function notificationId(departureId: string, slot: number): number {
  const base = hashString(departureId) % 0x1fffffff;
  return base * SLOT_COUNT + slot;
}

function allSlotIds(departureId: string): number[] {
  return [0, 1, 2, 3].map((slot) => notificationId(departureId, slot));
}

/**
 * Deterministic notification id for a sprint's single end-of-sprint alarm.
 *
 * A sprint only ever gets one alarm (not four staged ones like a
 * departure), so there's no real slot to assign — but the id still has to
 * live somewhere that can't collide with `notificationId`'s departure ids.
 * The tempting-looking fix is a disjoint numeric range (e.g. widen
 * SLOT_COUNT, or shift sprint ids into the top half of the 31-bit space).
 * Both are wrong: SLOT_COUNT must stay 4, because changing it would change
 * what `notificationId(someExistingDepartureId, slot)` computes for every
 * departure already on a user's device, and cancelDepartureAlarms() has no
 * record of *what was actually scheduled* — only the ability to recompute
 * the same ids again. Silently recomputing different ids means an old
 * alarm can never be found and cancelled again.
 *
 * The actual fix: don't build a new range at all. Reuse
 * `notificationId(sprintId, 0)` as-is. This is safe because a departure id
 * and a sprint id are both `crypto.randomUUID()` values drawn from two
 * different tables that this app never compares to each other — so a hash
 * collision between "some departure's slot-0 startBy alarm" and "some
 * sprint's end alarm" is exactly the same already-documented,
 * theoretically-possible-but-accepted collision class `hashString()`
 * above already lives with (worst case: one alert silently overwrites or
 * cancels the other at that id, not data corruption). See
 * notifications.test.ts for the bit-width assertion this relies on.
 *
 * milestoneNotificationId (below) makes exactly the same call for the same
 * reason: a milestone also only ever gets one alarm (its morning-of
 * reminder), and a milestone id is drawn from the same `crypto.randomUUID()`
 * id space as departures and sprints, so `notificationId(milestoneId, 0)`
 * is just as safe to reuse here as it was for sprints.
 */
export function sprintNotificationId(sprintId: string): number {
  return notificationId(sprintId, 0);
}

/**
 * Deterministic notification id for a milestone's single morning-of alarm —
 * same reuse rationale as sprintNotificationId directly above (read that
 * comment for the full "why not a disjoint range" argument). Kept as its
 * own named function, rather than callers writing `notificationId(id, 0)`
 * inline, purely so a milestone id and a sprint id are never visually
 * interchangeable at a call site even though they resolve to the same
 * formula.
 */
export function milestoneNotificationId(milestoneId: string): number {
  return notificationId(milestoneId, 0);
}

/**
 * Deterministic notification id for one study-block occurrence (Prüfung
 * rework 2). Namespaced on `date` as well as `examId` — unlike a sprint or
 * a milestone, which only ever gets ONE alarm for its whole lifetime, a
 * study schedule materializes one alarm PER matching day, and each needs
 * its own id to be individually cancellable without disturbing the rest of
 * the week's blocks.
 *
 * Reuses `notificationId` with a namespaced STRING key
 * (`study-${examId}-${date}`) rather than adding a disjoint numeric range —
 * same reuse rationale as `sprintNotificationId`/`milestoneNotificationId`
 * above: it's the string, not a slot number, that keeps this id
 * distinguishable from any departure/sprint/milestone id already drawn from
 * the same 32-bit hash space, and a hash collision between them carries the
 * exact same already-accepted "one alarm silently overwrites another, not
 * data corruption" risk `hashString`'s own comment documents. `date` (not a
 * full instant) is deliberate too: it's the same stable join key
 * `occurrenceDates`/`calendarDates` (src/lib/recurrence.ts) already produce,
 * so `scheduleStudyBlockAlarms` (this week's real schedule) and
 * `cancelStudyBlockAlarms` (a blunter 14-day date walk, no schedule needed)
 * always agree on what id a given day means, even though only one of them
 * ever computes the day's exact alarm TIME.
 */
export function studyBlockNotificationId(examId: string, date: string): number {
  return notificationId(`study-${examId}-${date}`, 0);
}

/** Pure array-map wrapper around `studyBlockNotificationId`, extracted so
 * `cancelStudyBlockAlarms`'s 14-day window and this file's own tests can
 * both depend on one place deciding what "the ids for these dates" means,
 * rather than each recomputing the mapping inline and risking the two
 * drifting apart. */
export function studyBlockNotificationIds(examId: string, dates: string[]): number[] {
  return dates.map((date) => studyBlockNotificationId(examId, date));
}

/**
 * Cancels any of the four staged alarms currently pending for a departure.
 * Safe to call unconditionally — cancel() silently ignores ids that aren't
 * pending (never scheduled, already fired, or already cancelled), which is
 * exactly what "terminal status cancels alarms" and "reschedule on edit"
 * both need without first checking what's actually pending.
 *
 * `name` (activity-log increment) is for the log line only — see
 * `logEvent`'s own header comment for why a name is an accepted narrow
 * exception to this log's usual name-free rule. Every real call site
 * already has the full `Departure` in scope (Runway.tsx's handlers, Home's
 * `removeDeparture`, materialize.ts's sweep, and `scheduleDepartureAlarms`
 * below, which calls this as its own first step) — this function is called
 * unconditionally even when nothing was actually pending, so a "cancelled"
 * line here means "the app asked the OS to cancel," not "something was
 * definitely armed a moment ago."
 */
export async function cancelDepartureAlarms(departureId: string, name: string): Promise<void> {
  if (!Capacitor.isNativePlatform()) return;
  await LocalNotifications.cancel({
    notifications: allSlotIds(departureId).map((id) => ({ id })),
  });
  void logEvent('alarm', `Alarms cancelled: ${name}.`);
}

/**
 * Cancels any existing alarms for this departure, then schedules whichever
 * of the four staged times (src/lib/alarmTimes.ts) are still in the future.
 * `leaveNow` (slot 3) goes to the high-importance LEAVE_CHANNEL_ID
 * ('runway-leave-2') channel; the other three go to the gentler
 * STAGED_CHANNEL_ID ('runway-staged-2') channel.
 *
 * `allowWhileIdle: true` is what makes these fire through Doze with the app
 * closed (RUNWAY_PLAN.md §5.5) — Android still rate-limits idle alarms to
 * roughly once per 9 minutes per app, which is a non-issue here since the
 * four slots are always spaced further apart than that in any real
 * departure plan.
 */
export async function scheduleDepartureAlarms(departure: Departure): Promise<void> {
  if (!Capacitor.isNativePlatform()) return;
  await ensureChannels();
  await cancelDepartureAlarms(departure.id, departure.name);

  const alarms = computeAlarmTimes(new Date(), departure);
  if (alarms.length === 0) return;

  const options: ScheduleOptions = {
    notifications: alarms.map((alarm) => ({
      id: notificationId(departure.id, alarm.slot),
      title: 'Runway',
      body: `${alarm.copy} ${departure.name}`,
      channelId: alarm.slot === 3 ? LEAVE_CHANNEL_ID : STAGED_CHANNEL_ID,
      schedule: { at: alarm.at, allowWhileIdle: true },
      extra: { departureId: departure.id },
      // F2: only slot 0 ("Start getting ready.") gets a snooze button. The
      // other three stages are deliberately excluded — "Wrap up" already
      // means the buffer has started, and "Leave in 5"/"Leave now" snoozing
      // themselves would be self-deception with a UI: the appointment
      // doesn't move just because the alarm did, so a snoozed "leave now"
      // only produces a later, still-just-as-real lateness. "Start getting
      // ready" is the one stage where 10 more minutes is still a plan
      // change Replan-from-now (F1) can absorb, not a promise the rest of
      // the schedule can't keep.
      actionTypeId: alarm.slot === 0 ? START_ACTION_TYPE_ID : undefined,
    })),
  };
  await LocalNotifications.schedule(options);
  void logEvent('alarm', `Alarms armed: ${departure.name}.`);
}

/**
 * Schedules the single alarm for a sprint's planned end, on the same
 * high-importance LEAVE_CHANNEL_ID ('runway-leave-2') channel a departure's
 * "leave now" alert uses — a sprint's timer going off is a real event (RUNWAY_PRUFUNG_PLAN.md
 * §5: "a timer ringing is real, not simulated"), not a softer nudge.
 *
 * Scheduled once, at sprint start, for startedAt + plannedMinutes. Reaching
 * that instant does NOT end the sprint (Sprint.tsx keeps the countdown
 * running past zero, into overrun) — this alarm is purely informational,
 * telling Deepak the box of time is up, not stopping anything itself.
 *
 * No-ops if that instant has already passed — scheduling a notification for
 * a moment already behind us isn't meaningful, and there's no legitimate
 * caller of this that would ever need it (it's only ever invoked once, at
 * sprint creation, with a startedAt of "now").
 */
export async function scheduleSprintEndAlarm(sprint: Sprint, topicName: string): Promise<void> {
  if (!Capacitor.isNativePlatform()) return;
  await ensureChannels();

  const endAt = new Date(new Date(sprint.startedAt).getTime() + sprint.plannedMinutes * MS_PER_MINUTE);
  if (endAt.getTime() <= Date.now()) return;

  await LocalNotifications.schedule({
    notifications: [
      {
        id: sprintNotificationId(sprint.id),
        title: 'Runway',
        body: `Sprint complete. ${topicName}`,
        channelId: LEAVE_CHANNEL_ID,
        schedule: { at: endAt, allowWhileIdle: true },
        extra: { sprintId: sprint.id },
      },
    ],
  });
}

/**
 * Cancels a sprint's end alarm, if one is still pending — same "safe to
 * call unconditionally" reasoning as cancelDepartureAlarms: cancel()
 * silently ignores an id that was never scheduled, already fired, or
 * already cancelled.
 */
export async function cancelSprintEndAlarm(sprintId: string): Promise<void> {
  if (!Capacitor.isNativePlatform()) return;
  await LocalNotifications.cancel({ notifications: [{ id: sprintNotificationId(sprintId) }] });
}

/**
 * Cancels a milestone's pending morning-of alarm, if one exists. Same
 * "safe to call unconditionally" reasoning as cancelSprintEndAlarm/
 * cancelDepartureAlarms above. Called from two places: MilestoneEdit's
 * delete action (a deleted milestone has nothing left to remind about), and
 * from inside scheduleMilestoneAlarm itself, below, ahead of every
 * (re)schedule — the same "cancel whatever was there, then schedule fresh"
 * shape scheduleDepartureAlarms uses, so an edited milestone's alarm always
 * reflects its latest saved name/date rather than layering a new
 * notification on top of a stale one at the same id.
 */
export async function cancelMilestoneAlarm(milestoneId: string): Promise<void> {
  if (!Capacitor.isNativePlatform()) return;
  await LocalNotifications.cancel({ notifications: [{ id: milestoneNotificationId(milestoneId) }] });
}

/**
 * Schedules a milestone's single morning-of alarm (RUNWAY_PRUFUNG_PLAN.md
 * §5): whichever is EARLIER of 07:30 LOCAL time on the milestone's own
 * calendar date, or the milestone's own time (F9) — "Today: {name}, {HH:mm}."
 * is meant to land while Deepak is still getting his day started, not at
 * the moment the milestone happens (that's what the milestone itself is
 * for). Built with plain Date mutators (`setHours`), which operate in the
 * device's local timezone — the same "local", not UTC, time the rest of
 * this app's date math assumes.
 *
 * The min(07:30, milestone.at) clamp (F9) matters for an early milestone —
 * a 06:00 mock oral, say. Unconditionally reminding "this morning" at 07:30
 * would fire the reminder AFTER the thing it's reminding about has already
 * started, which defeats the point of a morning-of nudge entirely. Clamping
 * to the milestone's own time instead means the reminder is never later
 * than useful, even though it stops being a true "before the day starts"
 * nudge for milestones that early.
 *
 * On the gentler STAGED channel, not the high-importance LEAVE channel a
 * sprint's end alarm uses: a milestone reminder is a heads-up for later
 * today, not an "act now" alert the way a sprint timer or a departure's
 * leave-now stage is.
 *
 * No `extra` payload and no special navigation on tap (increment-4 spec):
 * tapping just opens the app to wherever it was, same as any other cold
 * launch. The exam overview is one tap from Home, so wiring a dedicated
 * "jump straight to this milestone" path isn't worth the complexity for
 * what this alarm is — a nudge to open the app, not a deep link.
 *
 * Skips scheduling (past-filter rule, same as computeAlarmTimes for
 * departures) if the clamped reminder time has already passed — Android
 * fires a past-scheduled exact alarm immediately, and a stale "Today: ..."
 * reminder firing the moment you save an edit would be surprising, not
 * useful.
 */
export async function scheduleMilestoneAlarm(milestone: Milestone): Promise<void> {
  if (!Capacitor.isNativePlatform()) return;
  await ensureChannels();
  await cancelMilestoneAlarm(milestone.id);

  const milestoneAt = new Date(milestone.at);
  const morningOf = new Date(milestoneAt);
  morningOf.setHours(7, 30, 0, 0);
  // F9: min(07:30 that day, milestone.at) — see the doc comment above.
  const remindAt = morningOf.getTime() < milestoneAt.getTime() ? morningOf : milestoneAt;
  if (remindAt.getTime() <= Date.now()) return;

  await LocalNotifications.schedule({
    notifications: [
      {
        id: milestoneNotificationId(milestone.id),
        title: 'Runway',
        body: `Today: ${milestone.name}, ${formatTime(milestoneAt)}.`,
        channelId: STAGED_CHANNEL_ID,
        schedule: { at: remindAt, allowWhileIdle: true },
        // No `extra` — see the doc comment above: tapping opens the app via
        // the plugin's default behaviour, deliberately not wired to any
        // special navigation the way a departure's `extra.departureId` is.
      },
    ],
  });
}

/**
 * How many days ahead `cancelStudyBlockAlarms` walks when clearing pending
 * study-block ids — deliberately WIDER than `HORIZON_DAYS` (the window
 * `scheduleStudyBlockAlarms` actually plans). A schedule that just shrank
 * (a day removed, or Study blocks turned off) leaves no schedule object
 * behind that could tell a fresh cancel pass which dates used to matter, so
 * this has to over-cancel by calendar date alone rather than under-cancel
 * by trusting whatever the CURRENT schedule says. 14, not just `HORIZON_DAYS`
 * doubled for no reason: it covers every id any past `scheduleStudyBlockAlarms`
 * call could have minted (that call never plans further than `HORIZON_DAYS`
 * out) with a full week of slack for how long Runway might go unopened
 * between materializer passes.
 */
const STUDY_BLOCK_CANCEL_WINDOW_DAYS = 14;

/**
 * Cancels every study-block alarm that could currently be pending for
 * `exam` — the next `STUDY_BLOCK_CANCEL_WINDOW_DAYS` calendar dates' worth
 * of ids (see that constant's own comment for why the window is wider than
 * what's ever actually scheduled). Safe to call unconditionally, same
 * "cancel() silently ignores an id that isn't pending" reasoning as
 * `cancelDepartureAlarms` — called both standalone (Study blocks toggled
 * off) and as the first step of `scheduleStudyBlockAlarms` below (toggled
 * on, or edited).
 */
export async function cancelStudyBlockAlarms(exam: Exam): Promise<void> {
  if (!Capacitor.isNativePlatform()) return;
  const dates = calendarDates(new Date(), STUDY_BLOCK_CANCEL_WINDOW_DAYS);
  await LocalNotifications.cancel({
    notifications: studyBlockNotificationIds(exam.id, dates).map((id) => ({ id })),
  });
}

/**
 * Prüfung rework 2's structural fix, made real: cancels whatever was
 * pending for `exam`, then schedules one alarm per occurrence
 * `exam.studySchedule` produces over the next `HORIZON_DAYS` — exactly
 * `occurrenceDates` (src/lib/recurrence.ts), reused verbatim, the same
 * function `materializeScheduledDepartures` already relies on for
 * departures. No-ops (after the cancel) when `exam.studySchedule` is null —
 * a schedule just turned off should leave nothing armed, not a stale set of
 * alarms from before.
 *
 * Deliberately NOTIFICATION-ONLY: there is no `studyBlocks` table and no row
 * created per occurrence (binding decision, db/types.ts's `Exam.studySchedule`
 * doc comment). A study block that's never started should vanish without
 * trace — the weekly hours bar (ExamOverview) is already the honest record
 * of what actually happened, and a guilt ledger of skipped blocks would only
 * fight that. A block that IS started becomes a real `Sprint` through the
 * normal SprintSetup flow, which is the only record this app keeps of study
 * time — this function's whole job is getting Deepak to that flow at the
 * moment he chose, not bookkeeping the moments he didn't.
 *
 * Body copy is fixed and literal ("Study block. {exam.name}") — no
 * per-occurrence detail to report, since there's no row behind the alarm to
 * describe one. `actionTypeId` reuses `START_ACTION_TYPE_ID`, the same
 * snooze action type a departure's "Start getting ready" alarm gets: "not
 * yet, ten more minutes" is exactly as legitimate a response to a study
 * block alarm as to a departure one, and a second, near-identical action
 * type would only duplicate that one button for no behavioural difference.
 * `extra: { studyBlock: true, examId }` is what `registerNotificationNavigation`
 * below reads to route a tap into SprintSetup instead of a departure.
 */
export async function scheduleStudyBlockAlarms(exam: Exam): Promise<void> {
  if (!Capacitor.isNativePlatform()) return;
  await ensureChannels();
  await cancelStudyBlockAlarms(exam);
  if (exam.studySchedule == null) {
    void logEvent('alarm', 'Study-block alarms re-armed.');
    return;
  }

  const occurrences = occurrenceDates(new Date(), exam.studySchedule, HORIZON_DAYS);
  if (occurrences.length === 0) {
    void logEvent('alarm', 'Study-block alarms re-armed.');
    return;
  }

  await LocalNotifications.schedule({
    notifications: occurrences.map((occurrence) => ({
      id: studyBlockNotificationId(exam.id, occurrence.date),
      title: 'Runway',
      body: `Study block. ${exam.name}`,
      channelId: STAGED_CHANNEL_ID,
      schedule: { at: occurrence.at, allowWhileIdle: true },
      extra: { studyBlock: true, examId: exam.id },
      actionTypeId: START_ACTION_TYPE_ID,
    })),
  });
  void logEvent('alarm', 'Study-block alarms re-armed.');
}

/**
 * Whether Android's per-app "use exact alarms" toggle is on. Always
 * 'granted' on web/dev (there's no such setting to check, and we don't want
 * a banner to ever show outside native). See checkExactNotificationSetting
 * in the plugin's definitions.d.ts — the exact_alarm field of its result is
 * itself a PermissionState ('granted' | 'denied' | 'prompt' |
 * 'prompt-with-rationale'); anything other than 'granted' is treated as
 * "off" for the purposes of the Home banner (§6 of this increment's spec).
 */
export async function getExactAlarmStatus(): Promise<'granted' | 'denied'> {
  if (!Capacitor.isNativePlatform()) return 'granted';
  const status = await LocalNotifications.checkExactNotificationSetting();
  return status.exact_alarm === 'granted' ? 'granted' : 'denied';
}

/**
 * Opens Android's exact-alarm settings screen for this app (via the
 * plugin's changeExactNotificationSetting — its doc comment notes that on
 * Android < 12 there is no such screen and it resolves 'granted' directly
 * instead of navigating anywhere; either way this call is safe to fire and
 * forget). No-ops on web/dev.
 */
export async function openExactAlarmSettings(): Promise<void> {
  if (!Capacitor.isNativePlatform()) return;
  await LocalNotifications.changeExactNotificationSetting();
}

/**
 * Registers the tap-to-open handler once, for the lifetime of the app.
 * Returns an unsubscribe function so the caller (App.tsx, in a mount
 * effect) can clean up under React 18 StrictMode's double-invoke.
 *
 * `onStudyBlockTap` (Prüfung rework 2) is a second, narrower callback rather
 * than widening `handler`'s own signature: `handler` exists specifically to
 * hand back a departure id (main.tsx's `navigateToDeparture` needs exactly
 * that), and a study-block tap has no departure id to offer — it always
 * means the same one destination (SprintSetup, prefilled), so a callback
 * that takes no argument says that plainly instead of a `string | null`
 * `handler` would have to branch on internally.
 *
 * Cold-start caveat (increment-4 spec §4): @capacitor/local-notifications
 * has no getLaunchNotification()-style API — unlike
 * @capacitor/push-notifications, this plugin's definitions.d.ts exposes no
 * way to ask "was the app just launched by tapping a notification".
 * @capacitor/app isn't part of this increment's plugin list either, so
 * there's no fallback API available to check that reliably.
 *
 * Capacitor's native bridge is generally documented to buffer
 * notifyListeners() calls that fire before any JS listener has attached,
 * and deliver them once one does — which would mean registering this
 * listener at the very top of the app (main.tsx, before the first React
 * render) also catches the cold-start-by-tap case. That's inferred
 * general Capacitor bridge behaviour, not something this plugin's .d.ts
 * documents or guarantees, so treat "tapping a notification while the app
 * is fully closed opens the right departure" as UNVERIFIED until tested on
 * a real device — this is the flagged <90%-certain item for this increment.
 */
export async function registerNotificationNavigation(
  handler: (departureId: string) => void,
  onStudyBlockTap: () => void,
): Promise<() => void> {
  if (!Capacitor.isNativePlatform()) return () => {};

  const listenerHandle = await LocalNotifications.addListener(
    'localNotificationActionPerformed',
    (action: ActionPerformed) => {
      // F2: tapping "Snooze 10 min" reschedules instead of opening the app
      // (see scheduleSnoozeAlarm's own doc comment). This branch runs
      // identically for a study-block alarm as for a departure one —
      // scheduleSnoozeAlarm reschedules whatever `original` notification was
      // tapped, unconditionally, using ITS OWN id/title/body/channel/
      // actionTypeId/extra, so a snoozed study block keeps its
      // `extra.studyBlock` flag (and therefore still routes through the
      // `onStudyBlockTap` branch below) the next time it fires, with no
      // study-block-specific code needed here. Every other actionId — in
      // practice just 'tap', the plugin's default for tapping the
      // notification body itself (read the .d.ts's ActionPerformed comment)
      // — falls through to the two branches below.
      if (action.actionId === SNOOZE_ACTION_ID) {
        void scheduleSnoozeAlarm(action.notification);
        return;
      }
      // Prüfung rework 2: a tapped study-block alarm has no departure to
      // open — it routes into SprintSetup's prefilled start flow instead
      // (main.tsx wires `onStudyBlockTap` to
      // `navigateToScreen({ name: 'sprintSetup', autoSuggest: true })`).
      // Checked before the departure branch below since a study-block
      // notification's `extra` has no `departureId` to fall through on
      // anyway, but checking explicitly keeps the two kinds of alarm this
      // file schedules clearly separated rather than relying on one
      // silently not matching the other's shape.
      if (action.notification.extra?.studyBlock === true) {
        onStudyBlockTap();
        return;
      }
      const departureId = action.notification.extra?.departureId;
      if (typeof departureId === 'string') {
        void logEvent('navigation', 'Notification tap: departure.');
        handler(departureId);
      }
    },
  );

  return () => {
    void listenerHandle.remove();
  };
}

/**
 * F2: re-schedules the tapped "Start getting ready." alarm
 * `SNOOZE_MINUTES` from the moment "Snooze 10 min" was tapped, reusing the
 * ORIGINAL notification's id/title/body/channel/actionTypeId/extra exactly
 * — this is a pure reschedule of the same alarm, not a resend of possibly-
 * stale copy computed from whatever the departure looks like now. Reusing
 * `original.id` (== notificationId(departureId, 0)) matters beyond just
 * "why compute a new one": it's what keeps the snoozed alarm cancellable
 * through the exact same path everything else already uses —
 * cancelDepartureAlarms recomputes that same id on leave/abandon/edit, so a
 * snooze taken and then overtaken by one of those still gets cleaned up
 * without this function needing to know about it.
 *
 * Deliberately does NOT navigate anywhere, unlike a tap — snoozing means
 * "not yet"; popping the app open to the Runway screen the instant you ask
 * for ten more minutes would defeat the point of asking.
 *
 * Device-verify item, same class as registerNotificationNavigation's own
 * cold-start caveat above: this handler only runs at all if Capacitor's
 * bridge can wake the JS runtime from an app-fully-closed state on an
 * action tap — inferred general bridge behaviour (the same "buffers events
 * until a listener attaches" mechanism the cold-start tap case already
 * relies on), not something this plugin's .d.ts documents as guaranteed.
 * UNVERIFIED until tested on a real device with the app fully closed.
 */
async function scheduleSnoozeAlarm(original: LocalNotificationSchema): Promise<void> {
  const snoozeAt = new Date(Date.now() + SNOOZE_MINUTES * MS_PER_MINUTE);
  await LocalNotifications.schedule({
    notifications: [
      {
        id: original.id,
        title: original.title,
        body: original.body,
        channelId: original.channelId,
        actionTypeId: original.actionTypeId,
        schedule: { at: snoozeAt, allowWhileIdle: true },
        extra: original.extra,
      },
    ],
  });
}
